### ISSUE TITLE
Active Directory Dependency Issue on Azure Functions 

### ISSUE THREAD

**Issue by TonyAbell** [codehollow/AzureBillingApi#1]
Due to an issue with the Active Directory Library for Dotnet [ADL] v3 this library will not work in Azure Functions.
[Issue](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/511)

I was able to downgrade [ADL] to 2.28.4 and everything works fine.

**Comment by arminreiter** [comment]
It seems that the [issue](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/511) is fixed in newer versions, so I updated the ADL to a new version.
