### ISSUE TITLE
Usage and costs for Azure marketplace items

### ISSUE THREAD

**Issue by consultguru** [codehollow/AzureBillingApi#2]
Can codehollow/AzureBillingAPI get data for Azure marketplace items?
e.g. say we deploy a firewall or an anti-virus software from Azure marketplace

And in general, What are the use-cases that are now available using the API?

**Comment by arminreiter** [comment]
codehollow/AzureBillingAPI uses the [Azure Billing REST API](https://msdn.microsoft.com/en-us/library/azure/mt218998.aspx) to read usage and resource cost data. It is a wrapper for the REST API. Additionally to that, it combines the usage data with the cost rates per resource and calculates the costs real costs. 

There it depends on the given REST API which does currently afaik not support marketplace items (but feel free to try it).

Use cases: you can use it to analyze your costs, It can give you detailed information about the usage and the resource rates. The sample console application creates 3 CSV files with the data from the billing api - usage, rates and costs (combination of usage and rates).
